# 1 Numpy

In [2]:
import numpy as np

In [4]:
revenus = [1222, 2000, 3000, 4000]
revenus_array = np.array(revenus)

In [5]:
revenus_array.shape

(4,)

In [7]:
hugo = [1300, 400, 23]
richard = [1700, 560, 24]
emilie = [2500, 900, 30]
gaspard = [3000, 1000, 22]
yohann = [2400, 700, 28]

In [8]:
tableau = [hugo, richard, emilie, gaspard, yohann]

In [9]:
data = np.array(tableau)

In [10]:
data

array([[1300,  400,   23],
       [1700,  560,   24],
       [2500,  900,   30],
       [3000, 1000,   22],
       [2400,  700,   28]])

In [11]:
data[0,1]

400

In [12]:
data[3, :]

array([3000, 1000,   22])

In [13]:
data[data[:, 0] < 2000]

array([[1300,  400,   23],
       [1700,  560,   24]])

In [14]:
fred = [1800, 500, 32]

In [17]:
data = np.vstack((data, fred))

In [18]:
data

array([[1300,  400,   23],
       [1700,  560,   24],
       [2500,  900,   30],
       [3000, 1000,   22],
       [2400,  700,   28],
       [1800,  500,   32]])

In [19]:
a = np.linspace(5,10,11)
a

array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [20]:
print(a[-3:-1])

[9.  9.5]


In [26]:
b = np.array([[[1,2],[4,5]],[[1,2],[4,5]],[[10,2],[4,5]]])

In [27]:
b[2,:,:]

array([[10,  2],
       [ 4,  5]])