# 1 Numpy

In [17]:
import numpy as np

In [18]:
revenus = [1222, 2000, 3000, 4000]
revenus_array = np.array(revenus)

In [19]:
revenus_array.shape

(4,)

In [20]:
hugo = [1300, 400, 23]
richard = [1700, 560, 24]
emilie = [2500, 900, 30]
gaspard = [3000, 1000, 22]
yohann = [2400, 700, 28]

In [21]:
tableau = [hugo, richard, emilie, gaspard, yohann]

In [22]:
data = np.array(tableau)

In [23]:
data

array([[1300,  400,   23],
       [1700,  560,   24],
       [2500,  900,   30],
       [3000, 1000,   22],
       [2400,  700,   28]])

In [24]:
data[0,1]

400

In [25]:
data[3, :]

array([3000, 1000,   22])

In [26]:
data[data[:, 0] < 2000]

array([[1300,  400,   23],
       [1700,  560,   24]])

In [27]:
fred = [1800, 500, 32]

In [28]:
data = np.vstack((data, fred))

In [29]:
data

array([[1300,  400,   23],
       [1700,  560,   24],
       [2500,  900,   30],
       [3000, 1000,   22],
       [2400,  700,   28],
       [1800,  500,   32]])

In [30]:
a = np.linspace(5,10,11)
a

array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [31]:
print(a[-3:-1])

[9.  9.5]


In [32]:
b = np.array([[[1,2],[4,5]],[[1,2],[4,5]],[[10,2],[4,5]]])

In [33]:
b[2,:,:]

array([[10,  2],
       [ 4,  5]])

# 2 Pandas

In [35]:
import pandas as pd

In [36]:
data = pd.read_csv('data_2/clients.csv')
data.headad()

AttributeError: 'DataFrame' object has no attribute 'headad'

In [5]:
data_json = pd.read_json('data_2/clients.json')
data_json.headad()

identifiant                      email               nom genre
0            0  LaurentDagenais@rhyta.com  Laurent Dagenais     M
1            1      GuyMarois@fleckens.hu        Guy Marois     M
2            2  BeaufortLesage@einrot.com   Beaufort Lesage     M
3            3  RussellDurand@armyspy.com    Russell Durand     M
4            4       AlexisRiel@rhyta.com       Alexis Riel     M

In [6]:
data_excel = pd.read_excel('data_2/clients.xlsx')

In [7]:
data_excel.head()

identifiant                      email               nom genre
0            0  LaurentDagenais@rhyta.com  Laurent Dagenais     M
1            1      GuyMarois@fleckens.hu        Guy Marois     M
2            2  BeaufortLesage@einrot.com   Beaufort Lesage     M
3            3  RussellDurand@armyspy.com    Russell Durand     M
4            4       AlexisRiel@rhyta.com       Alexis Riel     M

In [8]:
clients_array = data_excel.values
clients_array

array([[0, 'LaurentDagenais@rhyta.com', 'Laurent Dagenais', 'M'],
       [1, 'GuyMarois@fleckens.hu', 'Guy Marois', 'M'],
       [2, 'BeaufortLesage@einrot.com', 'Beaufort Lesage', 'M'],
       [3, 'RussellDurand@armyspy.com', 'Russell Durand', 'M'],
       [4, 'AlexisRiel@rhyta.com', 'Alexis Riel', 'M'],
       [5, 'LeonLapresse@cuvox.de', 'Leon Lapresse', 'M'],
       [6, 'OrvilleRouthier@gustr.com', 'Orville Routhier', 'M'],
       [7, 'AgramantPepin@dayrep.com', 'Agramant Pepin', 'M'],
       [8, 'AiglentinaLambert@fleckens.hu', 'Aiglentina Lambert', 'F'],
       [9, 'TheodoreClavet@teleworm.us', 'Theodore Clavet', 'M'],
       [10, 'ByronLefebvre@jourrapide.com', 'Byron Lefebvre', 'M'],
       [11, 'FlorusDevoe@einrot.com', 'Florus Devoe', 'M'],
       [12, 'NormandArsenault@armyspy.com', 'Normand Arsenault', 'M'],
       [13, 'AcelineHughes@jourrapide.com', 'Aceline Hughes', 'F'],
       [14, 'GastonBrisette@superrito.com', 'Gaston Brisette', 'M'],
       [15, 'AgateGrandbois@gus

In [9]:
email = data_excel['email']
email

0            LaurentDagenais@rhyta.com
1                GuyMarois@fleckens.hu
2            BeaufortLesage@einrot.com
3            RussellDurand@armyspy.com
4                 AlexisRiel@rhyta.com
                    ...               
223    ClaudeDandonneau@jourrapide.com
224      ApollineMichaud@superrito.com
225         PascalineBeaudry@rhyta.com
226       FleurCaouette@jourrapide.com
227        FrancisMasse@jourrapide.com
Name: email, Length: 228, dtype: object

In [10]:
data.iloc[0,2]

'Laurent Dagenais'

In [14]:
data.iloc[:5, 1:3]

email               nom
0  LaurentDagenais@rhyta.com  Laurent Dagenais
1      GuyMarois@fleckens.hu        Guy Marois
2  BeaufortLesage@einrot.com   Beaufort Lesage
3  RussellDurand@armyspy.com    Russell Durand
4       AlexisRiel@rhyta.com       Alexis Riel

In [40]:
data.groupby('genre')['nom'].sum()

genre
F    Aiglentina LambertAceline HughesAgate Grandboi...
M    Laurent DagenaisGuy MaroisBeaufort LesageRusse...
Name: nom, dtype: object

In [41]:
notes = pd.read_csv('data_2/notes.csv')

In [47]:
notes.head()

nom   matiere  note
0  Laurent Dagenais  Français    16
1        Guy Marois  Français    13
2   Beaufort Lesage  Français     8
3    Russell Durand  Français    10
4       Alexis Riel  Français    15

In [49]:
moyenne = notes.groupby('nom').mean()
moyenne.loc[moyenne['note'] < 10].shape[0]

6

In [51]:
produits = pd.read_csv('data_2/produits.csv')
commandes = pd.read_csv('data_2/commande.csv')

In [52]:
produits.head()

id  prix
0   0  24.8
1   1  13.1
2   2  23.7
3   3  16.0
4   4  19.0

In [53]:
commandes.head()

id  nombre
0  70       2
1  41       4
2  72       2
3  92       8
4  73       1

In [65]:
total = pd.merge(produits, commandes, on='id', how='left')
total = total.groupby('id')['nombre'].sum().sort_values()
total

id
58      6
28     15
62     20
92     20
29     21
     ... 
30     89
84     91
65     96
35     98
8     103
Name: nombre, Length: 100, dtype: int64

In [68]:
total2 = pd.merge(produits, total, on = 'id', how='left')
total2['ca'] = total2['prix']*total2['nombre']
total2.sort_values(by=['ca'])

id  prix  nombre      ca
58  58  23.8       6   142.8
92  92   7.4      20   148.0
63  63   8.5      22   187.0
29  29  10.8      21   226.8
62  62  13.0      20   260.0
..  ..   ...     ...     ...
27  27  24.5      86  2107.0
19  19  31.6      67  2117.2
30  30  24.9      89  2216.1
65  65  26.3      96  2524.8
8    8  25.6     103  2636.8

[100 rows x 4 columns]